### ISSUE TITLE
Customize floating window size

### ISSUE THREAD

**Issue by dbernheisel** [conweller/findr.vim#13]
Heyo,
Is there a way to customize the floating window? I'd like to personalize it so it opens on the left at full height. [Other plugins like fzf](https://github.com/junegunn/fzf/blob/6db15e86937029b4a4565b2ae73a3c6bae5ef4ba/plugin/fzf.vim#L663-L671) allow the user to pass in a dict that can be used by nvim when opening the floating window

I'll be happy to submit a PR if you think this is a good idea. Let me know if you have any implementation thoughts.

I have it mostly working locally but can't seem to figure out how to evaluate a viml string like `"call FindrFloatingWindow()"` within lua and store the dict result. [I'm thinking this is where the user-supplied dict would need to land.](https://github.com/conweller/findr.vim/blob/b2b82d78e5d65fab403dcae9cb7ba435efa256ee/lua/findr/view/window.lua#L14-L32). If you have any tips, it might get me over the bump and submit a PR.

I'm thinking something like:

```viml
" if g:findr_floating_window = 1, then continue using the default layout
let g:findr_floating_window = {
  \ 'window': 'call FindrFloatingWindow()'
  \ }

function! FindrFloatingWindow()
  return {
    \ 'relative': 'editor',
    \ 'row': 0,
    \ 'col': 0,
    \ 'height': &lines - 2,
    \ 'width': float2nr(&columns / 2)
    \ }
endfunction
```

**Comment by conweller** [comment]
I think that would definitely be a good feature. There might be a more elegant way to do it, but I think you can get it to work using `vim.api.nvim_get_var()` and `vim.api.nvim_call_function`, i.e. something like:
```lua
local winfunc = vim.api.nvim_get_var('findr_floating_window')['window']
local winopts = vim.api.nvim_call_function(winfunc, {})
```
You would just have to change the `g:findr_floating_window` dict to:
```vim
let g:findr_floating_window = {
  \ 'window': 'call FindrFloatingWindow()'
  \ }
```
If you want to look at the documentation for `nvim_get_var`, `nvim_call_function`, and other similar functions, you can checkout:
```
:h api.txt
```
All of the functions in there can be called in lua files with `vim.api.<api-function-name>`
