### ISSUE TITLE
Provide option to not abbreviate file names

### ISSUE THREAD

**Issue by eullerborges** [conweller/findr.vim#15]
Fantastic work with the plugin! This really feels like ivy/helm.

It'd be great to have a configuration to not abbreviate the path when not using the floating window, as it's rather rare to fill the whole screen in that scenario.

**Comment by conweller** [comment]
Awesome to hear that you like it! Yeah that makes a lot of sense, I'll add an option for configuring the way the path is displayed in the next day or so!

**Comment by conweller** [comment]
Just made some changes to address this:
- By default the path will only be abbreviated if there's not enough room to display the full path
- You can use`let g:findr_shorten_path = 2` to always abbreviate the path
- You can use`let g:findr_shorten_path = 0` to never abbreviate the path

**Comment by eullerborges** [comment]
Impressive! Now it works exactly how I imagined. Thanks a lot!
