### ISSUE TITLE
<c-h> and <bs> to move to parent dir not working in Vim 8.2

### ISSUE THREAD

**Issue by mikemc** [conweller/findr.vim#21]
Hi, I am using Vim/GVim 8.2 on Arch Linux, and the `<c-h>` and `<bs>` functionality doesn't work in file-finder mode. (I think it worked when I first installed Findr so this might have to do with a change in Vim). To check that it wasn't a problem with my config, I loaded just the latest Findr with a minimal test vimrc. I also verified that the behavior works within Neovim with the same configuration. Typing `<bs>` just does usual backspacing, and `<c-h>` causes the current file prompt to get duplicated.

Let me know if you'd like any more info. I'm pretty new to debugging Vim plugins so am not sure what other info would be useful. In the meantime I will use this as some motivation to start migrating to Neovim ;)

**Comment by conweller** [comment]
I think it must have been something I've changed, I don't think I've updated vim at all since I made this plugin, and I'm getting the same issue you're describing.

I think these change should hopefully fix it for you: #22 #23

**Comment by mikemc** [comment]
Yep, it seems to be working fine now, thanks! I'll go ahead and close the issue.
