### ISSUE TITLE
remove "../" and "./"

### ISSUE THREAD

**Issue by fiplox** [conweller/findr.vim#25]
Hello. I've been using findr for quite some time and find annoying having to scroll through "../' and "./". Found that you use `ls -a` as command. Wouldn't it be nicer to use `ls -A` ? ;)

btw, thank you for this great plugin :)

**Comment by conweller** [comment]
Glad to hear that you find the plugin useful! That's a good suggestion, I'll now set `ls -A` as the default `ls` command:

#28
